INSERT INTO dicts (uz, en) VALUES
('salom', 'hello'),
('rahmat', 'thank you'),
('yaxshi', 'good'),
('hayot', 'life'),
('do''st', 'friend'),
('oilaviy', 'family'),
('maktab', 'school'),
('kitob', 'book'),
('qiziqarli', 'interesting'),
('sevimli', 'favorite'),
('yashash', 'to live'),
('safar', 'journey'),
('sog''lom', 'healthy'),
('qiziqish', 'curiosity'),
('maqsad', 'goal'),
('kuchli', 'strong'),
('to''liq', 'full'),
('yo''l', 'road'),
('hujjat', 'document'),
('qadimgi', 'ancient'),
('tashrif', 'visit'),
('muhim', 'important'),
('mas''uliyat', 'responsibility'),
('tadqiqot', 'research'),
('maktabga', 'to school'),
('ish', 'work'),
('doira', 'circle'),
('suzish', 'swimming'),
('yurak', 'heart'),
('yovvoyi', 'wild'),
('hayvon', 'animal'),
('shahar', 'city'),
('qishloq', 'village'),
('tabiat', 'nature'),
('boshqaruv', 'management'),
('o''qimoq', 'to read'),
('yazmoq', 'to write'),
('eslatma', 'reminder'),
('qol', 'hand'),
('ko''z', 'eye'),
('quloq', 'ear'),
('og''z', 'mouth'),
('bosh', 'head'),
('barmoq', 'finger'),
('dislokatsiya', 'dislocation'),
('xuddi', 'just like'),
('sabzavot', 'vegetable'),
('meva', 'fruit'),
('pishloq', 'cheese'),
('non', 'bread'),
('suv', 'water'),
('chai', 'tea'),
('qahva', 'coffee'),
('baliq', 'fish'),
('go''sht', 'meat'),
('shirinlik', 'dessert'),
('pasta', 'pasta'),
('boshqalar', 'others'),
('jamiyat', 'society'),
('madaniyat', 'culture'),
('tarix', 'history'),
('ilm', 'science'),
('texnologiya', 'technology'),
('kompyuter', 'computer'),
('internet', 'internet'),
('mobil', 'mobile'),
('telefon', 'phone'),
('muhit', 'environment'),
('himo', 'protection'),
('tashkilot', 'organization'),
('sport', 'sport'),
('musobaqa', 'competition'),
('sog''lomlashtirish', 'rehabilitation'),
('sog''liq', 'health'),
('xavfsizlik', 'safety'),
('ta''lim', 'education'),
('o''qituvchi', 'teacher'),
('talaba', 'student'),
('fan', 'subject'),
('sinov', 'test'),
('dars', 'lesson'),
('mashg''ulot', 'exercise'),
('ko''rsatma', 'instruction'),
('malaka', 'qualification'),
('ma''lumot', 'information'),
('mashina', 'car'),
('yo''lovchi', 'passenger'),
('haydovchi', 'driver'),
('yo''l harakati', 'traffic'),
('avtobus', 'bus'),
('tren', 'train'),
('safarbarlik', 'mobilization'),
('tashqi', 'external'),
('ichki', 'internal'),
('imkoniyat', 'opportunity'),
('muvaffaqiyat', 'success'),
('maqsadga', 'to the goal');